server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml # This location needs to be writeable by Promtail.

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
 - job_name: nginx_log
  #  pipeline_stages:
   static_configs:
   - targets:
      - loki
     labels:
      job: varlogs  # A `job` label is fairly standard in prometheus and useful for linking metrics and logs.
      __path__: /opt/nginx/access.log  # The path matching uses a third party library: https://github.com/bmatcuk/doublestar
